[book]
authors = ["Tensor Frame Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Tensor Frame Documentation"
description = "A high-performance, PyTorch-like tensor library for Rust with multiple computational backends"

[build]
build-dir = "book"
create-missing = true

[preprocessor.links]

[preprocessor.index]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/yourusername/tensor-frame"
edit-url-template = "https://github.com/yourusername/tensor-frame/edit/main/docs/src/{path}"

[output.html.print]
enable = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.playground]
runnable = true
