name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: [self-hosted, gpu-testing]
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache dependencies
        id: cache-key
        uses: Swatinem/rust-cache@v2

  check-format:
    needs: setup
    runs-on: [self-hosted, gpu-testing]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check code format
        run: make fmt-check

  test-cpu:
    needs: setup
    runs-on: [self-hosted, gpu-testing]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run cpu tests
        run: make test-cpu

  test-wgpu:
    needs: setup
    runs-on: [self-hosted, gpu-testing]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run wgpu tests
        run: make test-wgpu

  test-cuda:
    needs: setup
    runs-on: [self-hosted, gpu-testing]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run cuda tests
        run: make test-cuda

  check-examples:
    needs: setup
    runs-on: [self-hosted, gpu-testing]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check examples
        run: make check-examples