name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: [self-hosted]
    name: Test and Format Check
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      # - name: Format code
      #   run: make fmt

      # - name: Auto-commit formatting changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: 'style: Auto-format code with cargo fmt'
      #     file_pattern: '*.rs'

      - name: Run cpu tests
        run: make test-cpu
      - name: Run wgpu tests
        run: make test-wgpu
      - name: Run cuda tests
        run: make test-cuda