name: CI

on:
  push:
    branches: [ main, develop ]
    on:
      - '**/*.rs'
      - '**/*.sh'
      - '**/*.cu'
      - '**/*.wgsl'
      - 'Cargo.toml'
      - 'Makefile'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main, develop ]
    on:
      - '**/*.rs'
      - '**/*.sh'
      - '**/*.cu'
      - '**/*.wgsl'
      - 'Cargo.toml'
      - 'Makefile'
      - '.github/workflows/ci.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  Setup:
    runs-on: [self-hosted, gpu-testing]
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache dependencies
        id: cache-key
        uses: Swatinem/rust-cache@v2

  Check format:
    needs: setup
    runs-on: [self-hosted, gpu-testing]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check code format
        run: make fmt-check

  Test CPU:
    needs: setup
    runs-on: [self-hosted, gpu-testing]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run cpu tests
        run: make test-cpu

  Test WGPU:
    needs: setup
    runs-on: [self-hosted, gpu-testing]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run wgpu tests
        run: make test-wgpu

  Test CUDA:
    needs: setup
    runs-on: [self-hosted, gpu-testing]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run cuda tests
        run: make test-cuda

  Check examples:
    needs: setup
    runs-on: [self-hosted, gpu-testing]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check examples
        run: make check-examples